framework:
    router:
        # optionnel → seulement utile pour CLI / emails
        default_uri: 'https://chats-libres-local.onrender.com'

when@prod:
    framework:
        router:
            strict_requirements: null